appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: b3/PgpO71iTCafK58PtbcT4SnjGyW23MNREgdalc6gtC1zbXRMzCD81tnOB1DSZm70bQuCS+KbNr2jCYAY79Z6tqE2Vm6Idw02kijZ/M7KiYQhNQL+Hfcc/6id0Tb3ogFN1TpoN6RXIW69Jd08YAhBTIpjTju2rAKQB/y4VijC3ssZxaA7Rx2bG6rZ9WgfvOTo3iWF8IfanF5lebnUPokFJPy3qfOnkWqYPS7CIRPyxEFVQ4piuSd3xqBE2Q5Kme5buw+x1RqZV9cFWryVmSIXUIr59/t0ixlzybUI7SR1EN27Il8Wne3dA/RPf5u28Ii6DPpbb6hNHV+Q5CGix7Begw7/FRR9HCaJ00qAAN4D0JNp9hYYuiI+Na+d4lCbBsT0MdCWa/OaRMT1r1RRMebeWfsV0C8sXmcQ64SlppUCROcPKCQP6oyPuTct5Lj7bY9MWZJeOMts4SgJn5ryeSxJcI9r3XFMrFTMkzunieq7mdM2xwL8ShRkmLdsINgh5AWZi1ip1PYfbS85TJCI9HNwKuObTcm/qOIZv3lTJvyatR1lpY4OccUAH2iFZrTfJCJMSjIOhOTbCWwTJEMj/l9l3yJa9KRk6n8veAgnju+QcTrgVrtYzSAy+9GswH9YOb9j4XkbMnfAlOlNRcCaztYZ/94Fbh62VkazX++JlFQxQ=}
